#       IDENTIFICATION DIVISION.
#       PROGRAM-ID. prog.
#       DATA DIVISION.
#       WORKING-STORAGE SECTION.
#       01 WS-PAGE-NUMBER PIC 9(4) COMP-3 VALUE ZERO.
#       01 WS-LINE-NUMBER PIC 9(3) VALUE ZERO.
#       PROCEDURE DIVISION.
#       PERFORM VARYING WS-LINE-NUMBER FROM 1 BY 1
#                 UNTIL WS-LINE-NUMBER > 10
#         ADD 1 TO WS-PAGE-NUMBER
#         DISPLAY WS-PAGE-NUMBER
#       END-PERFORM.
#       STOP RUN RETURNING 0.
#
