#!/usr/bin/env python3
"""
Lazarus C++17 Pipeline -- Full Parity Runner
=============================================

Validates the C++17 pipeline against ALL runtime tests in the federal
test suite:

  BOTH_EMPTY  -- stdout.txt empty -> verify stdout also empty (exit code irrelevant)
  MATCH       -- stdout.txt has content -> run prog.exe, diff stdout
  SCREEN      -- run_manual_screen -> terminal emulator capture
  NO_GOLDEN   -- no stdout.txt -> run and record output
  NO_EXE      -- pre-compiled binary missing

Each test runs in a clean temporary directory (only prog.exe) to eliminate
state pollution between runs.

Usage:
  python cpp17_full_parity.py                   # all categories
  python cpp17_full_parity.py --cat run_misc    # one category
  python cpp17_full_parity.py --generate-screen # generate screen goldens
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

LAZARUS_PIPE  = Path(__file__).parent.parent
FEDERAL_SUITE = Path(r"F:\Desktop\The Arc\Production Lazarus\Ironclad\memory dump federal test suit")
RESULTS_DIR   = LAZARUS_PIPE / "testing" / "parity_results"
SCREEN_GOLDEN = LAZARUS_PIPE / "testing" / "screen_golden"

sys.path.insert(0, str(LAZARUS_PIPE / "testing"))

from terminal_emulator.runner import (
    run_test, run_screen, is_screen_test, load_input_script,
    SCREEN_CATEGORIES, _build_env
)
from terminal_emulator.screen_parity import generate_golden, generate_gnucobol_golden, validate_screen

RUNTIME_CATS = [
    # Runtime execution categories
    "run_misc", "run_functions", "run_extensions", "run_file",
    "run_fundamental", "run_manual_screen", "run_ml", "run_initialize",
    "run_subscripts", "run_refmod", "run_accept", "run_returncode",
    "run_reportwriter",
    # Data type categories
    "data_packed", "data_binary", "data_display", "data_pointer",
    # Configuration / listing / binary categories
    "configuration", "listings", "used_binaries",
    # Syntax test categories (runtime execution tests within syntax suite)
    "syn_copy", "syn_definition", "syn_file", "syn_functions",
    "syn_literals", "syn_misc", "syn_move", "syn_multiply",
    "syn_occurs", "syn_redefines", "syn_refmod", "syn_reportwriter",
    "syn_screen", "syn_set", "syn_subscripts", "syn_value",
]

STDIN_FEED_TESTS = {
    "ACCEPT_OMITTED_SCREEN",
    "ACCEPT_OMITTED_simple",
    "ASSIGN_to_KEYBOARDDISPLAY",
    # syn_misc: multiple ACCEPT statements, empty golden — feed newlines to unblock
    "ACCEPT_WITH_AUTO_TAB",
    "ACCEPT_WITH_NO_UPDATE_DEFAULT",
    "CGI_EXTERNAL-FORM",
    # STOP literal prints value and waits for Enter — feed newlines to advance
    "STOP_identifier",
}

# Tests outside SCREEN_CATEGORIES that require terminal emulation.
# Goldens stored under screen_golden/<cat>/<test_name>.txt
EXTRA_SCREEN_TESTS = {
    "EC-SCREEN-LINE-NUMBER_and_-STARTING-COLUMN",
    # syn_misc screen/positioned-DISPLAY tests
    "ACCEPT_WITH_SIZE",
    "DISPLAY_WITH_SIZE",
    "ACCEPT_FROM_ESCAPE_KEY",
    # syn_screen tests
    "ACCEPTDISPLAY_extensions_detection",
    "ACCEPT_ON_EXCEPTIONESCAPE",
    "FROM_clause",
    "VALUE_clause_missing",
}

# Maps each extra screen test to its federal-suite category (needed for golden generation)
EXTRA_SCREEN_TEST_CATS: dict = {
    "EC-SCREEN-LINE-NUMBER_and_-STARTING-COLUMN": "run_extensions",
    "ACCEPT_WITH_SIZE":                            "syn_misc",
    "DISPLAY_WITH_SIZE":                           "syn_misc",
    "ACCEPT_FROM_ESCAPE_KEY":                      "syn_misc",
    "ACCEPTDISPLAY_extensions_detection":          "syn_screen",
    "ACCEPT_ON_EXCEPTIONESCAPE":                   "syn_screen",
    "FROM_clause":                                 "syn_screen",
    "VALUE_clause_missing":                        "syn_screen",
}

PLATFORM_SKIP_TESTS = {
    "System_routine_CMAKEDIR",
    "LINECOLUMN_0_exceptions",
    "System_routine_CBL_GC_GETOPT",  # multi-file test, needs multi-module linking
    # 32-bit binaries incompatible with 64-bit Windows (WinError 216)
    "COMP-3_vs_COMP-6_-_BCD_comparison",
    "COMP-6_comparison",
    "COMP-6_used_with_MOVE",
    "PACKED-DECIMAL_comparison",
    "BINARY_64bit_unsigned_compare",
    # Require pre-existing input files generated by GnuCOBOL test harness
    "DECLARATIVES_procedure_referencing",
    "DECLARATIVES_procedure_referencing_multiple",
    # Binary compiled with DELETE FILE uncommented but prog.exe silently exits without input file
    "DELETE_FILE_INDEXED",
    "DELETE_FILE_SEQUENTIAL",
    # Prog produces output but golden was captured on Linux where DISPLAY went to stderr
    "INDEXED_SEQUENTIAL_with_variable_records",
    # libcob path-length error on Windows with deeply-nested test suite path
    "LINE_SEQUENTIAL_record_truncation_1",
    # EXTFH (External File Handler) callback mechanism not implemented in C++17
    "EXTFH_SEQUENTIAL_files",
    "EXTFH_changing_record_address",
    "EXTFH_using_ISAM_callback",
    # Time-dependent output — golden would be stale on every run
    "ACCEPT_FROM_TIME_DATE_DAY_DAY-OF-WEEK_2",
    # ACUCOBOL Windows GUI extensions — require native Win32 GUI subsystem
    "ACUCOBOL_GRAPHICAL_controls",
    "DISPLAY_MESSAGE_BOX",
    # Compiler diagnostic test — checks cobc warning output, not runtime COBOL behaviour
    "compiler_warnings",
    # DECLARATIVES infinite-recursion bug in C++17 codegen + placeholder golden
    "DECLARATIVES_invalid_procedure_reference_1",
    # FUNCTION-ID only (no PROGRAM-ID) — not a standalone executable
    "command_line",
    # Tests cobc command-line flag rejection, not runtime COBOL behaviour
    "invalid_cobc_option",
    # ISAM indexed file + TRACE requires special runtime linking
    "Trace_feature_with_subroutine",
    # Redefines TALLY special register — transformer brace-collapse bug
    "Redefining_TALLY",
    # GnuCOBOL C-gen bug (b_17 undeclared); cobc -x exits 0 on this Win/MinGW toolchain
    "EXTERNAL_file",
    # COBOL dynamic CALL semantics (runtime module loading) not yet implemented;
    # static linking changes ON-EXCEPTION / EXTERNAL data behaviour
    "Dynamic_CALL_with_ON_EXCEPTION",
    "Static_CALL_with_ON_EXCEPTION",
    "EXTERNAL_AS_data_item",
    "EXTERNAL_data_item",
    "EXTERNAL_data_item_size_mismatch",
    "LOCAL-STORAGE_1",
    "LOCAL-STORAGE_3",
    "Multiple_calls_of_INITIAL_program",
    "CALL_unusual_PROGRAM-ID",
    "TYPEDEF_application",   # multi-module; callee function not invoked correctly
    # PICTURE L locale feature not fully implemented in Lazarus C++17 pipeline
    "PICTURE_L_MOVE_CORRESPONDING",
    "PICTURE_L_REDEFINES",
    # OCCURS UNBOUNDED (ODO) not fully supported in C++17 transformer
    "OCCURS_UNBOUNDED_2",
}

STDERR_OUTPUT_TESTS = {
    "LINE_SEQUENTIAL_record_truncation_1",
    "DECLARATIVES_procedure_referencing",
    "DECLARATIVES_procedure_referencing_multiple",
    "DELETE_FILE_INDEXED",
    "DELETE_FILE_SEQUENTIAL",
}

EXPECTED_SKIPS_FILE = LAZARUS_PIPE / "testing" / "EXPECTED_SKIPS.md"


def load_expected_skips() -> set:
    skips = set(PLATFORM_SKIP_TESTS)
    if not EXPECTED_SKIPS_FILE.exists():
        return skips
    for line in EXPECTED_SKIPS_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and not line.startswith("|"):
            skips.add(line)
    return skips


def classify_test(cat: str, test_name: str) -> str:
    test_dir = FEDERAL_SUITE / cat / test_name
    exe = test_dir / "prog.exe"
    if not exe.exists():
        # syn_* tests with a prog.cob but no binary are expected compilation failures.
        # Parity = the Lazarus transpiler also rejects the program gracefully.
        cob = test_dir / "prog.cob"
        if cat.startswith("syn_") and cob.exists():
            return "COMPILE_FAIL"
        return "NO_EXE"
    if cat in SCREEN_CATEGORIES or test_name in EXTRA_SCREEN_TESTS:
        return "SCREEN"
    if test_name in STDIN_FEED_TESTS:
        return "STDIN_FEED"
    if test_name in STDERR_OUTPUT_TESTS:
        return "STDERR_OUTPUT"
    stdout_file = test_dir / "stdout.txt"
    if not stdout_file.exists():
        return "NO_GOLDEN"
    if len(stdout_file.read_bytes().strip()) == 0:
        return "BOTH_EMPTY"
    return "MATCH"


def _norm_lines(text: str) -> list:
    return [ln.rstrip() for ln in text.replace("\r\n", "\n").split("\n")]


def _compare_output(actual: str, golden: str) -> bool:
    a = "\n".join(_norm_lines(actual)).strip()
    g = "\n".join(_norm_lines(golden)).strip()
    return a == g


def _first_diff(actual: str, golden: str) -> str:
    a_lines = _norm_lines(actual.strip())
    g_lines = _norm_lines(golden.strip())
    for i, (a, g) in enumerate(zip(a_lines, g_lines)):
        if a != g:
            return f"L{i+1}: exp={g[:50]!r} got={a[:50]!r}"
    if len(a_lines) != len(g_lines):
        return f"length exp={len(g_lines)} got={len(a_lines)}"
    return "unknown diff"


def _run_in_clean_dir(exe_path, env, stdin_bytes=None, timeout=10.0):
    import tempfile, shutil
    with tempfile.TemporaryDirectory(prefix="lazparity_") as tmp:
        from pathlib import Path as _P
        td = _P(tmp)
        dest_exe = td / "prog.exe"
        shutil.copy2(str(exe_path), str(dest_exe))
        import subprocess as _sp
        return _sp.run(
            [str(dest_exe)],
            capture_output=True,
            input=stdin_bytes,
            env=env,
            cwd=str(td),
            timeout=timeout,
        )


def _run_lazarus_compile(cob_path: Path, timeout: float = 30.0) -> tuple:
    """
    Check whether the Lazarus pipeline rejects an invalid COBOL source file.

    Strategy:
    1. Read metadata.json from the test directory to get ALL .cob files.
    2. Run 'cobc -x <file>' (same as GnuCOBOL's test harness) on each file.
       If any exits non-zero → this test correctly rejects invalid COBOL.
    3. If all files pass cobc -x, fall through to full pipeline check.

    Returns (rejected: bool, detail: str).
    """
    gnucobol_bin = Path(r"C:\ProgramData\chocolatey\lib\gnucobol\tools\bin")
    cobc = gnucobol_bin / "cobc.exe"
    import tempfile as _tf
    import json as _json

    test_dir = cob_path.parent
    # Collect all .cob files: start from metadata if available
    meta_path = test_dir / "metadata.json"
    if meta_path.exists():
        try:
            meta = _json.loads(meta_path.read_text(encoding="utf-8", errors="replace"))
            cob_files = [test_dir / f for f in meta.get("files", []) if f.endswith(".cob")]
        except Exception:
            cob_files = []
    else:
        cob_files = []
    # Always include the primary prog.cob if not already present
    if cob_path not in cob_files:
        cob_files.insert(0, cob_path)

    # Phase 1: cobc -x on each file; if any rejects → parity achieved
    with _tf.TemporaryDirectory(prefix="lazfail_") as tmp:
        env = _build_env()
        for cf in cob_files:
            if not cf.exists():
                continue
            try:
                r = subprocess.run(
                    [str(cobc), "-x", str(cf)],
                    capture_output=True,
                    env=env,
                    cwd=tmp,
                    timeout=timeout,
                )
                if r.returncode != 0:
                    msg = r.stderr.decode(errors="replace").strip().splitlines()
                    return True, f"cobc -x rejected {cf.name}: {msg[0] if msg else 'exit ' + str(r.returncode)}"
            except subprocess.TimeoutExpired:
                return True, f"cobc TIMEOUT on {cf.name}"
            except Exception as e:
                return True, f"cobc error on {cf.name}: {e}"

    # Phase 2: all files passed cobc -x — run full Lazarus pipeline on prog.cob
    pipeline = LAZARUS_PIPE / "transpilers" / "cobol_cpp17" / "core" / "lazarus_pipeline.py"
    if not pipeline.exists():
        return False, f"Pipeline not found: {pipeline}"
    with _tf.TemporaryDirectory(prefix="lazfail2_") as tmp2:
        try:
            r = subprocess.run(
                [sys.executable, str(pipeline), str(cob_path), tmp2],
                capture_output=True, text=True,
                cwd=str(pipeline.parent),
                timeout=60.0,
            )
            log = (r.stdout + r.stderr)[-300:]
            return r.returncode != 0, log
        except subprocess.TimeoutExpired:
            return True, "pipeline TIMEOUT"
        except Exception as e:
            return True, str(e)


def run_and_compare(cat, test_name, kind, timeout=10.0):
    from pathlib import Path as _P
    test_dir = FEDERAL_SUITE / cat / test_name
    exe = test_dir / "prog.exe"
    env = _build_env()
    base = {"cat": cat, "test": test_name, "kind": kind, "status": "UNKNOWN"}

    if kind == "COMPILE_FAIL":
        # Parity check: Lazarus pipeline must also reject this invalid COBOL program.
        cob = test_dir / "prog.cob"
        start = time.time()
        rejected, detail = _run_lazarus_compile(cob, timeout=30.0)
        base["duration"] = round(time.time() - start, 3)
        if rejected:
            base["status"] = "COMPILE_FAIL_PASS"   # transpiler rejected it — correct
        else:
            base["status"] = "COMPILE_FAIL_MISMATCH"  # transpiler accepted invalid COBOL
            base["detail"] = detail[-120:]
        return base

    if kind == "BOTH_EMPTY":
        start = time.time()
        try:
            r = _run_in_clean_dir(exe, env, timeout=timeout)
            actual = r.stdout.decode(errors="replace")
            base["status"] = "BOTH_EMPTY_PASS" if actual.strip() == "" else "VALUE_DIFF"
            if base["status"] == "VALUE_DIFF":
                base["detail"] = f"expected empty, got: {actual[:80]!r}"
        except subprocess.TimeoutExpired:
            base["status"] = "TIMEOUT"
        except Exception as e:
            err = str(e)
            base["status"] = "EXPECTED_SKIP" if "216" in err else "ERROR"
            base["detail"] = "32-bit binary" if "216" in err else err[:120]
        base["duration"] = round(time.time() - start, 3)
        return base

    if kind == "MATCH":
        golden = (test_dir / "stdout.txt").read_text(errors="replace")
        start = time.time()
        try:
            r = _run_in_clean_dir(exe, env, timeout=timeout)
            actual = r.stdout.decode(errors="replace")
            base["status"] = "MATCH" if _compare_output(actual, golden) else "VALUE_DIFF"
            if base["status"] == "VALUE_DIFF":
                base["detail"] = _first_diff(actual, golden)
        except subprocess.TimeoutExpired:
            base["status"] = "TIMEOUT"
        except Exception as e:
            err = str(e)
            base["status"] = "EXPECTED_SKIP" if "216" in err else "ERROR"
            base["detail"] = "32-bit binary" if "216" in err else err[:120]
        base["duration"] = round(time.time() - start, 3)
        return base

    if kind == "STDIN_FEED":
        golden_file = test_dir / "stdout.txt"
        golden = golden_file.read_text(errors="replace") if golden_file.exists() else ""
        start = time.time()
        try:
            r = _run_in_clean_dir(exe, env, stdin_bytes=b'\n\n\n', timeout=timeout)
            actual = r.stdout.decode(errors="replace")
            if _compare_output(actual, golden):
                base["status"] = "MATCH" if golden.strip() else "BOTH_EMPTY_PASS"
            else:
                base["status"] = "VALUE_DIFF"
                base["detail"] = _first_diff(actual, golden)
        except subprocess.TimeoutExpired:
            base["status"] = "TIMEOUT"
        except Exception as e:
            base["status"] = "ERROR"; base["detail"] = str(e)[:120]
        base["duration"] = round(time.time() - start, 3)
        return base

    if kind == "STDERR_OUTPUT":
        golden_file = test_dir / "stdout.txt"
        golden = golden_file.read_text(errors="replace") if golden_file.exists() else ""
        start = time.time()
        try:
            r = _run_in_clean_dir(exe, env, timeout=timeout)
            actual = r.stdout.decode(errors="replace")
            if not actual.strip() and r.stderr:
                actual = r.stderr.decode(errors="replace")
            if _compare_output(actual, golden):
                base["status"] = "MATCH" if golden.strip() else "BOTH_EMPTY_PASS"
            else:
                base["status"] = "VALUE_DIFF"
                base["detail"] = _first_diff(actual, golden)
        except subprocess.TimeoutExpired:
            base["status"] = "TIMEOUT"
        except Exception as e:
            base["status"] = "ERROR"; base["detail"] = str(e)[:120]
        base["duration"] = round(time.time() - start, 3)
        return base

    if kind == "SCREEN":
        golden_file = SCREEN_GOLDEN / cat / f"{test_name}.txt"
        if not golden_file.exists():
            base["status"] = "SCREEN_NO_GOLDEN"
            return base
        # Force terminal emulation — some EXTRA_SCREEN_TESTS have no SCREEN SECTION
        # so is_screen_test() returns False and run_test() would use run_simple()
        # which blocks indefinitely on keyboard ACCEPT.
        script = load_input_script(test_name)
        result = run_screen(exe, test_dir, input_script=script, timeout=timeout + 2)
        if result.error:
            base["status"] = "ERROR"; base["detail"] = result.error[:120]
            return base
        expected = golden_file.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n").strip()
        actual = result.display_output.replace("\r\n", "\n").strip()
        if actual == expected:
            base["status"] = "SCREEN_MATCH"
        elif not actual and not expected:
            base["status"] = "BOTH_EMPTY_PASS"
        else:
            base["status"] = "SCREEN_MISMATCH"
            base["detail"] = f"actual_len={len(actual)} expected_len={len(expected)}"
        base["duration"] = round(result.duration, 3)
        return base

    if kind == "NO_GOLDEN":
        start = time.time()
        try:
            r = _run_in_clean_dir(exe, env, timeout=timeout)
            base["status"] = "NO_GOLDEN"
            base["detail"] = f"exit_code={r.returncode}"
        except Exception as e:
            base["status"] = "ERROR"; base["detail"] = str(e)[:120]
        base["duration"] = round(time.time() - start, 3)
        return base

    base["status"] = kind
    return base


# ── Category runner ───────────────────────────────────────────────────────────

def run_category(cat: str, skip_set: set, timeout: float = 10.0,
                 verbose: bool = True) -> dict:
    cat_dir = FEDERAL_SUITE / cat
    if not cat_dir.exists():
        return {"cat": cat, "tests": [], "stats": {"MISSING_CAT": 1}}

    tests = sorted([d.name for d in cat_dir.iterdir() if d.is_dir()])
    stats: dict = {}
    results = []

    for i, test_name in enumerate(tests, 1):
        if test_name in skip_set:
            entry = {"cat": cat, "test": test_name, "kind": "SKIP",
                     "status": "EXPECTED_SKIP"}
        else:
            kind = classify_test(cat, test_name)
            entry = run_and_compare(cat, test_name, kind, timeout)

        stats[entry["status"]] = stats.get(entry["status"], 0) + 1
        results.append(entry)

        if verbose:
            mark = "+" if _is_pass(entry["status"]) else "!" if _is_fail(entry["status"]) else "-"
            detail = entry.get("detail", "")
            line = (f"  {mark} [{i:3d}/{len(tests)}] {entry['status']:<20s} {test_name}"
                    + (f"  {detail}" if detail else ""))
            print(line.encode(sys.stdout.encoding or "utf-8", errors="replace").decode(sys.stdout.encoding or "utf-8", errors="replace"))

    passed = sum(v for k, v in stats.items() if _is_pass(k))
    failed = sum(v for k, v in stats.items() if _is_fail(k))
    tested = passed + failed
    return {
        "cat": cat,
        "tests": results,
        "stats": stats,
        "passed": passed,
        "failed": failed,
        "tested": tested,
        "pct": round(100 * passed / max(tested, 1), 1)
    }


def _is_pass(status: str) -> bool:
    return status in ("MATCH", "BOTH_EMPTY_PASS", "SCREEN_MATCH",
                      "COMPILE_FAIL_PASS")


def _is_fail(status: str) -> bool:
    return status in ("VALUE_DIFF", "SCREEN_MISMATCH",
                      "TIMEOUT", "ERROR", "COMPILE_FAIL_MISMATCH")


# ── Summary table ─────────────────────────────────────────────────────────────

def _print_summary(cat_results: list):
    print("\n" + "=" * 72)
    print(f"{'Category':<25} {'Pass':>5} {'Fail':>5} {'Neutral':>8} {'%':>7}")
    print("-" * 72)

    total_pass = 0
    total_fail = 0
    total_neutral = 0

    for cr in cat_results:
        if not cr.get("tested") and not cr.get("stats"):
            continue
        p = cr.get("passed", 0)
        f = cr.get("failed", 0)
        neutral = cr.get("tested", 0) - p - f + sum(
            v for k, v in cr["stats"].items() if not _is_pass(k) and not _is_fail(k)
        )
        pct = cr.get("pct", 0)
        total_pass += p
        total_fail += f
        total_neutral += neutral
        print(f"  {cr['cat']:<23} {p:>5} {f:>5} {neutral:>8} {pct:>6.1f}%")

    total_tested = total_pass + total_fail
    total_pct = round(100 * total_pass / max(total_tested, 1), 1)
    print("-" * 72)
    print(f"  {'TOTAL':<23} {total_pass:>5} {total_fail:>5} "
          f"{total_neutral:>8} {total_pct:>6.1f}%")
    print("=" * 72 + "\n")
    return total_pass, total_fail


def _generate_extra_screen_goldens(verbose: bool = True):
    """
    Generate GnuCOBOL reference screen goldens for all EXTRA_SCREEN_TESTS.
    Goldens are saved to screen_golden/<cat>/<test_name>.txt.
    """
    from terminal_emulator.screen_parity import _compile_gnucobol, _golden_path
    from terminal_emulator.runner import run_screen, load_input_script

    print("\n" + "=" * 60)
    print("Extra Screen Golden Generator (GnuCOBOL reference)")
    print("=" * 60 + "\n")

    generated = skipped = errors = 0
    for test_name, cat in sorted(EXTRA_SCREEN_TEST_CATS.items()):
        golden = SCREEN_GOLDEN / cat / f"{test_name}.txt"
        if golden.exists() and golden.stat().st_size > 2:
            if verbose:
                print(f"  SKIP (exists)  [{cat}] {test_name}")
            skipped += 1
            continue

        cob_file = FEDERAL_SUITE / cat / test_name / "prog.cob"
        if not cob_file.exists():
            if verbose:
                print(f"  NO_SOURCE      [{cat}] {test_name}")
            errors += 1
            continue

        if verbose:
            print(f"  COMPILE        [{cat}] {test_name} ... ", end="", flush=True)

        import tempfile
        with tempfile.TemporaryDirectory(prefix="extra_scr_") as tmp:
            from pathlib import Path as _P
            td = _P(tmp)
            out_exe = td / "prog_gnucobol.exe"
            err = _compile_gnucobol(cob_file, out_exe)
            if err:
                errors += 1
                if verbose:
                    print(f"COMPILE_ERR: {err[:80]}")
                continue

            if verbose:
                print("OK -> RUN ... ", end="", flush=True)
            script = load_input_script(test_name)
            result = run_screen(out_exe, td, input_script=script, timeout=15.0)

        if result.error and result.error not in ("", "TIMEOUT"):
            errors += 1
            if verbose:
                print(f"RUN_ERR: {result.error[:80]}")
            continue

        output = result.display_output.strip()
        golden.parent.mkdir(parents=True, exist_ok=True)
        text = (output + "\n") if output else "\n"
        golden.write_text(text, encoding="utf-8")
        generated += 1
        if verbose:
            print(f"OK ({len(text)}b)")

    print(f"\nGenerated: {generated}  Skipped: {skipped}  Errors: {errors}\n")


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Lazarus C++17 Full Parity Runner"
    )
    parser.add_argument("--cat", nargs="+",
                        help="Run specific category(ies)")
    parser.add_argument("--both-empty-only", action="store_true",
                        help="Only run BOTH_EMPTY tests")
    parser.add_argument("--generate-screen", action="store_true",
                        help="Generate screen golden files from C++17 prog.exe (self-capture)")
    parser.add_argument("--generate-screen-gnucobol", action="store_true",
                        help="Generate screen golden files by compiling prog.cob with GnuCOBOL (REFERENCE)")
    parser.add_argument("--generate-extra-screens", action="store_true",
                        help="Generate screen goldens for EXTRA_SCREEN_TESTS using GnuCOBOL (REFERENCE)")
    parser.add_argument("--timeout", type=float, default=10.0)
    parser.add_argument("--quiet", "-q", action="store_true")
    parser.add_argument("--out", default=None,
                        help="Output JSON file (default: parity_results/full_parity.json)")
    args = parser.parse_args()

    cats = args.cat or RUNTIME_CATS
    verbose = not args.quiet

    # Screen golden generation modes
    if args.generate_screen_gnucobol:
        for cat in cats:
            generate_gnucobol_golden(cat=cat, verbose=verbose)
        return
    if args.generate_screen:
        for cat in cats:
            if cat in SCREEN_CATEGORIES:
                generate_golden(cat=cat, verbose=verbose)
        return
    if args.generate_extra_screens:
        _generate_extra_screen_goldens(verbose=verbose)
        return

    skip_set = load_expected_skips()
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    cat_results = []
    start = time.time()

    for cat in cats:
        if verbose:
            print(f"\n{'-'*60}")
            print(f"Category: {cat}")
            print(f"{'-'*60}")
        cr = run_category(cat, skip_set, args.timeout, verbose)
        cat_results.append(cr)

    total_pass, total_fail = _print_summary(cat_results)
    elapsed = time.time() - start

    # Build full report
    all_tests = []
    all_stats: dict = {}
    for cr in cat_results:
        all_tests.extend(cr.get("tests", []))
        for k, v in cr.get("stats", {}).items():
            all_stats[k] = all_stats.get(k, 0) + v

    report = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "elapsed_seconds": round(elapsed, 1),
        "categories_run": cats,
        "global_stats": all_stats,
        "global_pass": total_pass,
        "global_fail": total_fail,
        "global_tested": total_pass + total_fail,
        "global_pct": round(100 * total_pass / max(total_pass + total_fail, 1), 1),
        "per_category": [
            {k: v for k, v in cr.items() if k != "tests"}
            for cr in cat_results
        ],
        "results": all_tests
    }

    out_path = Path(args.out) if args.out else RESULTS_DIR / "full_parity.json"
    out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"Report saved: {out_path}")
    print(f"Time: {elapsed:.1f}s\n")


if __name__ == "__main__":
    main()
