#       @OPTIONS ALPHAL(WORD)
#       @OPTIONS INITVALUE(100)
#       @OPTIONS INITVALUE(F)
#       @OPTIONS INITVALUE(AG)
#       @OPTIONS BINARY(WORD,MLBON) INITVALUE(00) NOTRUNC
#       @OPTIONS INITVALUE(00)
#       @OPTIONS NOTRUNC
#       @OPTIONS APOST,MAIN
#       @OPTIONS THREAD(SINGLE)
#       IDENTIFICATION DIVISION.
#       PROGRAM-ID. INVALID.
#
